In [3]:
import numpy as np
r = int(input("Enter the number of rows: "))
c = int(input("Enter the number of cols: "))
elems = list(map(int,input("Enter elements :").split()))
matrix = np.array(elems).reshape(r,c)
print(elems,'\n',matrix)

Enter the number of rows:  3
Enter the number of cols:  3
Enter elements : 1 2 3 4 5 6 7 8 9


[1, 2, 3, 4, 5, 6, 7, 8, 9] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


1. Write a numpy program to compute the sum of all elements, sum of each row and sum of each column of the given array.

In [13]:
ts = 0
print("Row Sum :")
for i in range(r):
    rs=0
    for j in range(c):
        rs = rs + matrix[i][j]
    print(rs)

print("\nColumn Sum :")
for j in range(c):
    cs = 0
    for i in range(r):
        cs = cs  + matrix[i][j]
    ts = ts + cs
    print(cs)

print("\nTotal Sum : ",ts)


Row Sum :
6
15
24

Column Sum :
12
15
18

Total Sum :  45


2. Write a numpy program to save a given array to a text file and load it

In [20]:
np.savetxt('array.txt',matrix)
matrix2= np.loadtxt('array.txt')
print("Original 2D array:")
print(matrix)
print("\nLoaded 2D array:")
print(matrix2)

Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Loaded 2D array:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


3. To check whether two arrays are equal or not (element-wise comparison) 

In [24]:
a = np.array([1,2,3,4,5])
b = np.array([9,8,7,6,5])
if(np.array_equal(a,b)):
    print("Equal")
else:
    print("Inequal")

Inequal


In [ ]:
4. Create a 4x4 array with random values and create a new array from the first array and swap the first and last row.

In [38]:
import random as rand
import numpy as np
elems = [rand.randint(1, 10) for _ in range(16)]
matrix = np.array(elems).reshape(4, 4)
print("First Array: \n\n",matrix)
elems2 = elems[12:16] + elems[4:12] + elems[0:4]
matrix2 = np.array(elems2).reshape(4, 4)
print("\nNew Array: \n\n",matrix2)



First Array: 

 [[ 8  5  2  9]
 [ 1 10  5 10]
 [ 6  8  8  9]
 [ 3 10  1  7]]

New Array: 

 [[ 3 10  1  7]
 [ 1 10  5 10]
 [ 6  8  8  9]
 [ 8  5  2  9]]


In [ ]:
5. To multiply 2 given arrays of same size, element by element

In [46]:
e = [rand.randint(1, 10) for _ in range(16)]
m1 = np.array(e).reshape(4, 4)
print("First Array: \n\n",m1)

e2 = [rand.randint(1, 10) for _ in range(16)]
m2 = np.array(e2).reshape(4, 4)
print("Second Array: \n\n",m2)

m3=[]
for i in range(4):
    row = []
    for j in range(4):
        row.append(m1[i][j] * m2[i][j])
    m3.append(row)

print("\nMultiplied Matrix:\n",np.array(m3).reshape(4,4))
        

First Array: 

 [[ 9  9  4  5]
 [10  7  2  1]
 [ 2  8  8  7]
 [ 1  2 10  9]]
Second Array: 

 [[7 6 1 3]
 [2 2 9 1]
 [2 5 1 2]
 [1 7 6 7]]

Multiplied Matrix:
 [[63 54  4 15]
 [20 14 18  1]
 [ 4 40  8 14]
 [ 1 14 60 63]]
