Matrix Operations

In [4]:
import numpy as np

In [5]:
a = [[1,2,3],[4,5,6],[7,8,9]]
c = np.array([1,2,3,4,5])
d = np.array([5,4,3,3,2])
print(d,c)

[5 4 3 3 2] [1 2 3 4 5]


Dot Product

In [6]:
print(np.dot(d,c))

44


Transpose

In [7]:
print("Matrix A is : ",a)
print("Transpose is : ")
print(np.transpose(a))

Matrix A is :  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Transpose is : 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


Inverse of a Matrix 

In [8]:
print(np.linalg.inv(a))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


Determinant of a Matrix

In [9]:
print(np.linalg.det(a))

-9.51619735392994e-16


Flatten a Matrix

In [14]:
b = np.array([1,2,3,4,5,6])
print(b.flatten())

[1 2 3 4 5 6]


Matrix Creation - Level : Noob

In [48]:
a = int(input("Enter the number of rows: "))
b = int(input("Enter the number of columns: "))
matrix=[]
for i in range(a):
    row=[]
    for j in range(b):
        elem = int(input())
        row.append(elem)
    matrix.append(row)
print(matrix)

Enter the number of rows:  3
Enter the number of columns:  3
 1
 2
 3
 4
 5
 6
 7
 8
 9


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Matrix Creation using 'list,map,split' - Level : Pro

In [16]:
r = int(input("Enter the number of rows: "))
c = int(input("Enter the number of cols: "))
elems = list(map(int,input("Enter elements :").split()))
matrix = np.array(elems).reshape(r,c)
print(elems,'\n',matrix)

Enter the number of rows:  2
Enter the number of cols:  3
Enter elements : 1 2 3 4 5 6


[1, 2, 3, 4, 5, 6] 
 [[1 2 3]
 [4 5 6]]


In [ ]:
Trace Of A Matrix : Sum of Diagonal Elements 

In [17]:
matrix.trace()

6

In [ ]:
Rank of a Matrix

In [22]:
print(np.linalg.matrix_rank(matrix))

2
