Excise 1
1. Create a 1-D array

In [3]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


2. Create a 2-D array

In [3]:
b=np.array([[1,2],[2,3]])
print(b)
print(type(b))

[[1 2]
 [2 3]]
<class 'numpy.ndarray'>


3. Array using "np.arange"

In [6]:
c=np.arange(5)
print(c)
print(type(c))

[0 1 2 3 4]
<class 'numpy.ndarray'>


4. User defined 1-D array

In [18]:
n=list(map(int,input("Enter numbers : ").split()))
d=np.array(n)
print(d)

Enter numbers :  1 2 3 4


[1 2 3 4]


5. User defined 2-D array

In [20]:
x=list(map(int,input("Enter 1st sub-list : ").split()))
y=list(map(int,input("Enter 2nd sub-list : ").split()))
e=np.array([x,y])
print(e)

Enter 1st numbers :  1 2 3
Enter 2nd numbers :  2 3 4


[[1 2 3]
 [2 3 4]]


6. Finding dimension of a array

In [26]:
print(c.shape)
print(e.shape)

(3,)
(2, 3)


7. Change shape of array

In [30]:
g=e.reshape(3,2)
print(g)

[[1 2]
 [3 2]
 [3 4]]


8. Matrix of n no of zeros

In [32]:
a = np.zeros(4)
print(a)
b = a.reshape(2,2)
print(b)

[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]


9. Identity matrix of size n

In [11]:
a=np.identity(4)

print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


10. User-defined elements in diagonal postion

In [12]:
a=np.diag([1,2,3,4,5])

print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


11. Comparison of arrays

In [14]:
L1 = np.array([1,2,3,4])
L2 = np.array([5,2,6,7])
gr=np.greater(L1,L2)
ge=np.greater_equal(L1,L2)
ls=np.less(L1,L2)
le=np.less_equal(L1,L2)
eq=np.equal(L1,L2)
print("L1>L2",gr,"\nL1>=L2",ge,"\nL1<L2",ls,"\nL1<=L2",le,"\nL1=L2",eq)

L1>L2 [False False False False] 
L1>=L2 [False  True False False] 
L1<L2 [ True False  True  True] 
L1<=L2 [ True  True  True  True] 
L1=L2 [False  True False False]


12. Write a numpy prgm to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15

In [18]:
a=np.arange(21)
print(a)
for i in a:
    if a[i]>=9 and a[i]<16:
        a[i]=a[i]*-1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


13.Sum of elements of array

In [30]:
a=np.array([[1,2,3],[3,4,5]])
print("Sum of columns : ",sum(a))
print("Sum of rows : ",a.sum(1))
print("Sum of array : ",a.sum())

Sum of columns :  [4 6 8]
Sum of rows :  [ 6 12]
Sum of array :  18


14. Create a random 4x4 matrix and swap 1st and Last row

In [36]:
import random
L1=[]
for i in range (4):
    L2=[]
    for j in range (4):
        L2.append(random.randint(2,9))
    L1.append(L2)
a=np.array(L1)
print("Original Matrix : \n",a)
a[[0,-1]]=a[[-1,0]]
print("\nMatrix after swapping : \n",a)

Original Matrix : 
 [[9 8 7 5]
 [9 9 4 2]
 [4 8 9 5]
 [8 8 3 4]]

Matrix after swapping : 
 [[8 8 3 4]
 [9 9 4 2]
 [4 8 9 5]
 [9 8 7 5]]


15. Multiply elements of an array

In [37]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
c=a*b
print("Product",c)

Product [ 2  6 12 20]
