Excise 1
1. Create a 1-D array

In [2]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


2. Create a 2-D array

In [3]:
b=np.array([[1,2],[2,3]])
print(b)
print(type(b))

[[1 2]
 [2 3]]
<class 'numpy.ndarray'>


3. Array using "np.arange"

In [6]:
c=np.arange(5)
print(c)
print(type(c))

[0 1 2 3 4]
<class 'numpy.ndarray'>


4. User defined 1-D array

In [18]:
n=list(map(int,input("Enter numbers : ").split()))
d=np.array(n)
print(d)

Enter numbers :  1 2 3 4


[1 2 3 4]


5. User defined 2-D array

In [20]:
x=list(map(int,input("Enter 1st sub-list : ").split()))
y=list(map(int,input("Enter 2nd sub-list : ").split()))
e=np.array([x,y])
print(e)

Enter 1st numbers :  1 2 3
Enter 2nd numbers :  2 3 4


[[1 2 3]
 [2 3 4]]


6. Finding dimension of a array

In [26]:
print(c.shape)
print(e.shape)

(3,)
(2, 3)


7. Change shape of array

In [30]:
g=e.reshape(3,2)
print(g)

[[1 2]
 [3 2]
 [3 4]]


8. Matrix of n no of zeros

In [32]:
a = np.zeros(4)
print(a)
b = a.reshape(2,2)
print(b)

[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
