In [4]:
a=2
b=6
c=a+b
print(c)

8


In [6]:
def swapped(a,b):
    a=a+b
    b=a-b
    a=a-b
    print("Swapped a = ",a," b = ",b) 
a=int(input("Enter 1st value : "))
b=int(input("Enter 2nd value : "))
swapped(a,b)

Enter 1st value :  5
Enter 2nd value :  7


Swapped a =  7  b =  5


In [11]:
def fib(n):
    a=0
    b=1
    for i in range(n):
        c=a+b
        print(a)
        a=b
        b=c
n=int(input("Enter limit : "))
fib(n)

Enter limit :  7


0
1
1
2
3
5
8


In [25]:
for i in range(5):
    for j in range(i):
        print(" * ")
    print(" ",end="")

  * 
  * 
 * 
  * 
 * 
 * 
  * 
 * 
 * 
 * 
 

In [26]:
import numpy as np

In [47]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
a.shape=(3,2)
print(a)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [38]:
type(a)

numpy.ndarray

In [45]:
b=a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [56]:
x=np.arange(1,24,3)
print(x)
y=np.arange(1,24,1.5)
print(y)

[ 1  4  7 10 13 16 19 22]
[ 1.   2.5  4.   5.5  7.   8.5 10.  11.5 13.  14.5 16.  17.5 19.  20.5
 22.  23.5]


In [62]:
a1=np.array([3,9,7])
print(a)
a2=np.array([17,9,11])
print(b)
result=np.greater_equal(a1,a2)
print(result)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[False  True False]


In [63]:
a3=np.arange(50,90,2)
print(a3)

[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88]


In [64]:
type(a3)

numpy.ndarray

In [67]:
a4=np.eye(4)
print(a4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [73]:
a5=np.zeros((5,5))
p=np.arange(1,5)
np.diagonal_set(a5,p)
print(a5)

AttributeError: module 'numpy' has no attribute 'diagonal_set'